server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffeec?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  
  datasource:
    hikari:
      main: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/coffeec?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
mybatis:
  type-aliases-package: com.lds.trackdayb.domain;com.lds.trackdayb.vo;com.lds.trackdayb.mvo;
  mapper-locations: mybatis/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
    